import { Movie } from '@models/Movie';

export const MovieData: Movie[] = [
  {
    kinopoiskId: 588,
    imdbId: 'tt0144084',
    nameRu: 'Американский психопат',
    nameEn: null,
    nameOriginal: 'American Psycho',
    posterUrl: 'https://kinopoiskapiunofficial.tech/images/posters/kp/588.jpg',
    webUrl: 'https://www.kinopoisk.ru/film/588/',
    year: 2000,
    filmLength: 102,
    ratingImdb: 7.2,
    ratingKinopoisk: 7.6,
  },
  {
    kinopoiskId: 403,
    imdbId: 'tt0083658',
    nameRu: 'Бегущий по лезвию',
    nameEn: null,
    nameOriginal: 'Blade Runner',
    posterUrl: 'https://kinopoiskapiunofficial.tech/images/posters/kp/403.jpg',
    webUrl: 'https://www.kinopoisk.ru/film/403/',
    year: 1982,
    filmLength: 117,
    ratingImdb: 7.7,
    ratingKinopoisk: 8.1,
  },
  {
    kinopoiskId: 95323,
    imdbId: 'tt0112159',
    nameRu: 'Евангелион',
    nameEn: null,
    nameOriginal: 'Shin Seiki Evangelion',
    posterUrl: 'https://kinopoiskapiunofficial.tech/images/posters/kp/95323.jpg',
    ratingKinopoisk: 8.1,
    ratingImdb: 8.5,
    webUrl: 'https://www.kinopoisk.ru/film/95323/',
    year: 1995,
    filmLength: 26,
  },
  {
    kinopoiskId: 95325,
    imdbId: 'tt0112159',
    nameRu: 'Евангелион 2',
    nameEn: null,
    nameOriginal: 'Shin Seiki Evangelion 2',
    posterUrl: 'https://kinopoiskapiunofficial.tech/images/posters/kp/95323.jpg',
    ratingKinopoisk: 8.1,
    ratingImdb: 8.5,
    webUrl: 'https://www.kinopoisk.ru/film/95323/',
    year: 1998,
    filmLength: 26,
  },
];
