import { Movie } from '../models/Movie';

export const MovieData: Movie[] = [
  {
    kinopoiskId: 588,
    kinopoiskHDId: '45030bde4844acdca70adeb33f92bd33',
    imdbId: 'tt0144084',
    nameRu: 'Американский психопат',
    nameEn: null,
    nameOriginal: 'American Psycho',
    posterUrl: 'https://kinopoiskapiunofficial.tech/images/posters/kp/588.jpg',
    posterUrlPreview: 'https://kinopoiskapiunofficial.tech/images/posters/kp_small/588.jpg',
    coverUrl:
      'https://avatars.mds.yandex.net/get-ott/200035/2a0000017c078f06bf98b117df5310532aa3/orig',
    logoUrl:
      'https://avatars.mds.yandex.net/get-ott/2439731/2a00000172173a2a7f76b918cc566ea98152/orig',
    reviewsCount: 231,
    ratingGoodReview: 81,
    ratingGoodReviewVoteCount: 159,
    ratingKinopoisk: 7.2,
    ratingKinopoiskVoteCount: 193838,
    ratingImdb: 7.6,
    ratingImdbVoteCount: 684074,
    ratingFilmCritics: 6.3,
    ratingFilmCriticsVoteCount: 154,
    ratingAwait: null,
    ratingAwaitCount: 0,
    ratingRfCritics: null,
    ratingRfCriticsVoteCount: 1,
    webUrl: 'https://www.kinopoisk.ru/film/588/',
    year: 2000,
    filmLength: 102,
    slogan: 'Респектабельная внешность дьявола',
    description:
      'Днем он ничем не отличается от окружающих, и в толпе вы не обратите на него внимания. Но ночью этот благовоспитанный гражданин превращается в изощренного убийцу, терроризирующего спящий город.\n\nСовременный дикарь, презирающий законы человечества, питается только испепеляющим пламенем своей ненависти, которая растет с каждым новым преступлением. Лавина ужаса приближается к критической черте. Скоро наступит момент, когда ее уже нельзя будет остановить.',
    shortDescription:
      'Страсть к совершенству превращает успешного брокера в жестокого убийцу. Культовый триллер с Кристианом Бэйлом',
    editorAnnotation: null,
    isTicketsAvailable: false,
    productionStatus: null,
    type: 'FILM',
    ratingMpaa: 'r',
    ratingAgeLimits: 'age18',
    startYear: null,
    endYear: null,
    serial: false,
    shortFilm: false,
    completed: false,
    hasImax: false,
    has3D: false,
    lastSync: '2023-11-08T01:14:28.657158',
  },
  {
    kinopoiskId: 403,
    kinopoiskHDId: '4048aa1d54bacf1eafe36cd31c7282ae',
    imdbId: 'tt0083658',
    nameRu: 'Бегущий по лезвию',
    nameEn: null,
    nameOriginal: 'Blade Runner',
    posterUrl: 'https://kinopoiskapiunofficial.tech/images/posters/kp/403.jpg',
    posterUrlPreview: 'https://kinopoiskapiunofficial.tech/images/posters/kp_small/403.jpg',
    coverUrl:
      'https://avatars.mds.yandex.net/get-ott/223007/2a0000017c0720f07c96366ac1a7a455579f/orig',
    logoUrl:
      'https://avatars.mds.yandex.net/get-ott/239697/2a000001746928346e55df8eef696e345928/orig',
    reviewsCount: 216,
    ratingGoodReview: 86,
    ratingGoodReviewVoteCount: 162,
    ratingKinopoisk: 7.7,
    ratingKinopoiskVoteCount: 191859,
    ratingImdb: 8.1,
    ratingImdbVoteCount: 804521,
    ratingFilmCritics: 8.5,
    ratingFilmCriticsVoteCount: 127,
    ratingAwait: null,
    ratingAwaitCount: 0,
    ratingRfCritics: null,
    ratingRfCriticsVoteCount: 1,
    webUrl: 'https://www.kinopoisk.ru/film/403/',
    year: 1982,
    filmLength: 117,
    slogan: 'A Futuristic Vision Perfected',
    description:
      'Ноябрь 2019 года. Бывший охотник на андроидов Рик Декард восстановлен в полиции Лос-Анджелеса для поиска возглавляемой Роем Батти группы репликантов, совершившей побег из космической колонии на Землю. В полиции считают, что андроиды пытаются встретиться с Эндолом Тайреллом — руководителем корпорации, которая разрабатывает кибернетический интеллект. Декард получает задание выяснить мотивы репликантов и уничтожить их.',
    shortDescription:
      'Детектив Декард преследует сбежавших андроидов. Культовый киберпанк Ридли Скотта о человеке и человечности',
    editorAnnotation: null,
    isTicketsAvailable: false,
    productionStatus: null,
    type: 'FILM',
    ratingMpaa: 'r',
    ratingAgeLimits: 'age16',

    startYear: null,
    endYear: null,
    serial: false,
    shortFilm: false,
    completed: false,
    hasImax: false,
    has3D: false,
    lastSync: '2023-11-07T20:17:39.116193',
  },
  {
    kinopoiskId: 95323,
    kinopoiskHDId: null,
    imdbId: 'tt0112159',
    nameRu: 'Евангелион',
    nameEn: null,
    nameOriginal: 'Shin Seiki Evangelion',
    posterUrl: 'https://kinopoiskapiunofficial.tech/images/posters/kp/95323.jpg',
    posterUrlPreview: 'https://kinopoiskapiunofficial.tech/images/posters/kp_small/95323.jpg',
    coverUrl: null,
    logoUrl: null,
    reviewsCount: 65,
    ratingGoodReview: 82,
    ratingGoodReviewVoteCount: 48,
    ratingKinopoisk: 8.1,
    ratingKinopoiskVoteCount: 68572,
    ratingImdb: 8.5,
    ratingImdbVoteCount: 81353,
    ratingFilmCritics: null,
    ratingFilmCriticsVoteCount: 0,
    ratingAwait: null,
    ratingAwaitCount: 0,
    ratingRfCritics: null,
    ratingRfCriticsVoteCount: 1,
    webUrl: 'https://www.kinopoisk.ru/film/95323/',
    year: 1995,
    filmLength: 26,
    slogan: 'Вы готовы к войне с ангелами?',
    description:
      '2015 год, Токио-3. 15 лет назад произошёл Второй удар, в результате чего Антарктида растаяла, Землю накрыла глобальная катастрофа, и большая часть человечества погибла. Теперь планету атакуют Ангелы — загадочные существа, противостоять которым могут только созданные с помощью биотехнологий гигантские роботы серии «Евангелион». \n\n14-летний Синдзи Икари направлялся на встречу с отцом, руководителем влиятельной организации NERV, когда Токио-3 подвергся нападению Ангела. С помощью капитана Мисато Кацураги парень добирается до подземной штаб-квартиры NERV и единственное, что он хочет сказать отцу — как сильно его ненавидит. Но на месте выясняется, что Синдзи должен прямо сейчас залезть в робота и сражаться с Ангелом.',
    shortDescription: null,
    editorAnnotation: null,
    isTicketsAvailable: false,
    productionStatus: null,
    type: 'TV_SERIES',
    ratingMpaa: null,
    ratingAgeLimits: 'age18',
    startYear: 1995,
    endYear: 1996,
    serial: true,
    shortFilm: false,
    completed: true,
    hasImax: false,
    has3D: false,
    lastSync: '2023-12-13T23:33:33.118723',
  },
];
