version: '3.8'

services:
  certificate:
    container_name: certificate
    build: 
      dockerfile: Dockerfile.cert
    volumes:
      - certificate:/app

  postgres:
    image: postgres
    hostname: ${POSTGRES_HOSTNAME}
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

  lobby-api:
    container_name: lobby-api
    build:
      context: ../LobbyService
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
      - certificate
    ports:
      - "5228:5228"
    volumes:
      - certificate:/app/cert
    environment:
      ConnectionStrings__DefaultConnectionString: "Host=${POSTGRES_HOSTNAME};Port=5432;Database=${POSTGRES_DATABASE};Username=${POSTGRES_USERNAME};Password=${POSTGRES_PASSWORD}"

  user-api:
    container_name: user-api
    build:
      context: ../UserService
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - certificate
    ports:
      - "5282:5282"
    volumes:
      - certificate:/app/cert
    environment:
      ConnectionStrings__DefaultConnectionString: "Host=${POSTGRES_HOSTNAME};Port=5432;Database=${POSTGRES_DATABASE};Username=${POSTGRES_USERNAME};Password=${POSTGRES_PASSWORD}"

  redis:
    image: "redis"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    container_name: redis-backplane
    environment:
      REDIS_CONNECTION_STRING: "${REDIS_HOST}:6379,password=${REDIS_PASSWORD}"
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - redis-network

  redis-commander:
    image: "rediscommander/redis-commander:latest"
    container_name: redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: root
    ports:
      - "8081:8081"
    networks:
      - redis-network


volumes:
  postgres-data:
  redis:
  redis-config:
  certificate:

networks:
  redis-network:
    driver: bridge
