version: '3.8'

services:
  postgres:
    image: postgres
    hostname: ${POSTGRES_HOSTNAME}
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_USER : ${POSTGRES_USERNAME}
      POSTGRES_DB : ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

  lobby-api:
    container_name: lobby-api
    build:
      context: ../LobbyService
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "5228:80"
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ConnectionStrings__DefaultConnectionString: "Host=${POSTGRES_HOSTNAME};Port=5432;Database=${POSTGRES_DATABASE};Username=${POSTGRES_USERNAME};Password=${POSTGRES_PASSWORD}"

  user-api:
    container_name: user-api
    build:
      context: ../UserService
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "5282:80"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionStrings__DefaultConnectionString: "Host=${POSTGRES_HOSTNAME};Port=5432;Database=${POSTGRES_DATABASE};Username=${POSTGRES_USERNAME};Password=${POSTGRES_PASSWORD}"

volumes:
  postgres-data: