version: '3.8'

services:
  postgres:
    image: postgres
    hostname: postgreshost
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: exposed!
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "5050:80"
    depends_on:
      - postgres
    
  lobby-api:
    build:
      context: ../LobbyService
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "5000:80"
    environment:
      ConnectionStrings__DefaultConnectionString: "Host=postgreshost;Port=5432;Database=postgres;Username=postgres;Password=exposed!"

volumes:
  postgres-data: