name: CI pipeline

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      webapp:  ${{ steps.changes.outputs.webapp }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            webapp:
              - 'src/WebApp/**'
  webapp:
    if: needs.changes.outputs.webapp == 'true'
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
  
      - name: Install dependencies
        run: cd ./src/WebApp && npm install
  
      - name: Lint
        run: cd ./src/WebApp && npm run lint
  
      - name: Build
        run: cd ./src/WebApp && npm run build
  pipeline:
    if: always()
    needs: [changes, webapp]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pass or fail
        run: |
          if [[ ${{ needs.webapp.result }} == "failure" || ${{ needs.webapp.result }} == "cancelled"]]; then
            exit 1
          else
            exit 0
          fi
