name: CI pipeline

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      webapp:  ${{ steps.changes.outputs.webapp }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            webapp:
              - '/src/WebApp/**'
  webapp:
    if: needs.changes.outputs.webapp == 'true'
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Webapp CI
        uses: ./.github/workflows/actions/webapp
  pipeline:
    needs: [changes, webapp]
    runs-on: ubuntu-latest
