name: CI pipeline

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Webapp CI
        uses: ./.github/workflows/webapp-ci
