name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to Server and Deploy
        run: |
          ssh root@${{ secrets.RUVDS_SERVER_IP }} "
            cd RollGo/src/Deploy
            git pull
            docker-compose up -d --build
          "
