name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      lobby:  ${{ steps.changes.outputs.lobby }}
      user:  ${{ steps.changes.outputs.user }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            webapp:
              - 'src/WebApp/**'
            lobby:
              - 'src/LobbyService/**'
            user:
              - 'src/UserService/**'
  deploy:
    if: needs.changes.outputs.lobby == 'true' || needs.changes.outputs.user == 'true'
    needs: changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to Server and Deploy
        run: |
          ssh root@${{ secrets.RUVDS_SERVER_IP }} -o StrictHostKeyChecking=no "
            cd RollGO/src/Deploy
            git pull
            docker compose up -d --build
          "
